application: Acme
psr4: 'app/Acme'
processed: false
dependencies: 
    flash: 
        enabled: true
        repo: 'laracasts/flash'
    html:
        enabled: true
        repo: 'illuminate/html'
    presenter:
        enabled: true
        repo: 'laracasts/presenter'
    debugbar:
        enabled: true
        repo: 'barryvdh/laravel-debugbar' 
    glide: 
        enabled: true
        repo: 'league/glide'
    medialibrary:
        enabled: true
        repo: 'spatie/laravel-medialibrary'
entities:
      - name: Albums
        processed: false
        model: true
        relationships:
          - type: hasMany
            model: Photos
            key1: album_id
            key2: 
        migration: true
        scaffold: true
        presentable: true
        media: true
        repository: true
        commands: true
        events: true
        controller: true
        requests: true
        routes: true
        admin:
            enabled: true
            scaffold: true
        fields:
            - name: name
              type: string
              nullable: false
              default: false
              default_value: false
            - name: slug
              type: string
              nullable: false
              default: false
              default_value: false
            - name: title
              type: string
              nullable: false
              default: false
              default_value: false
            - name: description
              type: string
              nullable: true
              default: false
              default_value: false
            - name: featured_photo_id
              type: integer
              nullable: true
              default: true
              default_value: false
      - name: Photos
        processed: false
        model: true
        relationships:
          - type: belongsTo
            model: Albums
            key1: album_id
            key2: 
        migration: true
        scaffold: true
        presentable: true
        media: true
        repository: true
        commands: true
        events: true
        controller: true
        requests: true
        routes: true
        admin:
            enabled: true
            scaffold: true
        fields:
            - name: path
              type: string
              nullable: false
              default: false
              default_value: false
            - name: album_id
              type: integer
              nullable: false
              default: false
              default_value: false

